### ISSUE TITLE
widetext* environment 

### ISSUE THREAD

**Issue by saghirb** [eddelbuettel/pinp#56]
Using the `widetext*` environment gives the following error:

```
! LaTeX Error: Environment widetext* undefined.
```
However if I use `widetext` then the error goes away (as it is defined in `pinp.cls`). It is also defined as `widetext` in `rticles::pnas_article`. For consistency I would change from  `\begin{widetext*} ... \end{widetext*}` to  `\begin{widetext} ... \end{widetext}` in the `pinp` vignette. 

Any thoughts/comments?

**Note:** Originally from [pull request #55](https://github.com/eddelbuettel/pinp/pull/55).

**Comment by eddelbuettel** [comment]
Just tested, and confirmed.  Which is super-weird, because I could _swear_ I tested that at some point (as it is so visible in the vignette).  Worst case the change is a side effect from something else.

But you are correct: this does not work as stated, and we should change to promoting `widetext` without an asterisk.
